### ISSUE TITLE
support for aws vpn client

### ISSUE THREAD

**Issue by jahlbornG** [sethcottle/tabcloser#5]
i wonder if you would be willing to add support for the aws vpn client?  when it is done authenticating, it leaves an authentication successful tab with the url "http://127.0.0.1:35001/".

**Comment by sethcottle** [comment]
@jahlbornG 

`127.0.0.1` is a loopback address—I'd be a little wary to add in detection to auto close any localhost addresses. For example, my VS Code Live Server runs at `127.0.0.1:5501`.

I would need to do more research into possibly just looking for an port `35001`, to see if that is unique to the AWS VPN client. If other services a user could have locally that could leverage that port (like looking at a localhost camera feed), I would not feel comfortable adding that to TabCloser. I'll do some legwork on `35001`, but it does look like it's [registered to ReadyTech](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5001) (looking at the Internet Assigned Numbers Authority) so it could be used a bit more broadly.

**Comment by jahlbornG** [comment]
well, TabCloser has the ability to turn closing on and off for a given type.  you could have it default to off and then users could turn it on if it fits their use case

**Comment by jahlbornG** [comment]
@sethcottle any chance of adding it as an "opt-in" url?

**Comment by sethcottle** [comment]
Heads-up, that I'm still looking into this! I'll likely be able to add it in, just haven't had the time since there's a little more changes I need to make to `background.js` than usual to disabled this one entry by default.

**Comment by sethcottle** [comment]
@jahlbornG hello hello!

![200w](https://github.com/user-attachments/assets/6cb82be4-3467-49e7-923f-4cfe19316fe7)

Okay, first of all, sorry this has taken me an insane amount of time to get to. Between work, life, other projects it's just been a nightmare finding the time. But with Google swapping Chrome to Manifest V3, it actually broke.... mostly everything about TabCloser. So I decided to rewrite the entire thing. It's taken me a hot minute, and I still have some work to do, but by the end of today, I am going to publish a dev branch for version 3.0 for testing.... it won't be super polished, I'll still want to do some UI updates, I'll probably still need to tweak some of the new code... but I built in with purpose this time, the ability to add custom URLs. Here's a little video of what it looks like right now!

https://github.com/user-attachments/assets/3f55588d-8e92-48a7-bc39-134b5d594201

**Comment by sethcottle** [comment]
Here's the [3.0 branch](https://github.com/sethcottle/tabcloser/tree/threedotzero). 

It still needs some work, so keep an eye out over the course of next week for all the final touch and improvements. I still need to do some testing a debugging, so do note that branch does have debug options set to `true`.

You're welcome to uninstall the version of TabCloser you have and installing from that branch to try it out and let me know what you think (and send any feedback/bugs you encounter since it's pretty much a rewrite). Once I have the final tweaks in and validate the test scenarios, I'll be publishing it to the store.

You can pull that branch down yourself or here's a pre-bundled .ZIP :
[tabcloser-3-debug.zip](https://github.com/user-attachments/files/16198563/tabcloser-3-debug.zip)

Note: with the way the new service workers are implemented, the closing times will be a little different than the current build. I'm still optimizing these, tabs will close, it just may take a little longer than usual for some.

**Introduces Custom URLs**

![Custom-URLs (1)](https://github.com/user-attachments/assets/0bc62e96-4c73-4914-9751-910ac2783b76)

**Redesigned Default Options**

![Frame-2 (2)](https://github.com/user-attachments/assets/2f85167f-2436-45ef-a463-427145d29e96)

**Comment by sethcottle** [comment]
New updates on the [TabCloser 3 branch](https://github.com/sethcottle/tabcloser/tree/threedotzero).

🗂️ [Download 3.0.1](https://github.com/user-attachments/files/16228450/tabcloser-3.0.1-debug.zip)

**Comment by jahlbornG** [comment]
@sethcottle  hey, sorry, never saw these updates.  just trying out the new version now.  works great, thanks!
