### ISSUE TITLE
Figma design tabs not auto-closing

### ISSUE THREAD

**Issue by MichaelMarcialis** [sethcottle/tabcloser#9]
Hello. Thanks for making this plugin. I use this plugin to auto-close Zoom join tabs and Figma file tabs. While it works fine for me with Zoom join tabs, it does not auto-close Figma design files. I have not yet tested Figma slide or Figjam files. Currently using Chrome 128.0.6613.120.

**Comment by sethcottle** [comment]
Hi @MichaelMarcialis, thanks for reporting this. I can look into it tonight; it's still been closing Figma files for me but there could be a variance somewhere I'm not catching.

If you wouldn't mind sending me a URL you know for a fact it did not close that would be wildly helpful to help diagnose. You don't need to post it publicly here if you don't want, you can email it if it's easier to me `sethcottle@gmail.com`.

**Comment by sethcottle** [comment]
Hi @MichaelMarcialis, thanks for reporting this. I can look into it tonight; it's still been closing Figma files for me but there could be a variance somewhere I'm not catching.

If you wouldn't mind sending me a URL you know for a fact it did not close that would be wildly helpful to help diagnose. You don't need to post it publicly here if you don't want, you can email it if it's easier: [seth@tabcloser.com](mailto:seth@tabcloser.com).

**Comment by sethcottle** [comment]
Haven't found any oddities tonight, but will keep testing. Tested with Chrome and Edge this evening, in both a Figma logged in and logged out state, where one is redirecting to Figma desktop and the other just opening straight up. Both working as intended and closing, since Figma isn't turned off in the options. 

Do you have anything in the settings toggled to `off` by chance? Just want to make sure there isn't some weird edge case interfering with anything.

**Chrome: Version 128.0.6613.138 (Official Build) (64-bit)**
![chrome](https://github.com/user-attachments/assets/21292c43-84c1-4da0-9554-d9acccb333de)

**Microsoft Edge: Version 128.0.2739.67 (Official build) (64-bit)**
![edge](https://github.com/user-attachments/assets/27cce7e2-f69c-4fbd-9595-67171022b4a7)

**My Settings**
![image](https://github.com/user-attachments/assets/6461ad42-4ace-4a6a-a3cf-e669767f7e55)
![image](https://github.com/user-attachments/assets/2b99f2ac-1a32-404d-a038-c1f3b26579bb)

**Comment by MichaelMarcialis** [comment]
Thanks for the response, @sethcottle. Strangely enough, I woke up this morning and the Figma tabs started auto-closing properly. No idea what I did to cause it, but chalking it up to user error. Closing this out.

**Comment by sethcottle** [comment]
Thanks @MichaelMarcialis! Let me know if anything else crops up, always happy to help. 😀
